import { Subscription, Alert, Budget, TeamMember, User, SavingsInsight } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Chen',
  email: 'alex@example.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  tier: 'pro',
  createdAt: new Date('2024-01-15'),
};

export const popularSaasTools = [
  { name: 'Slack', logo: 'https://logo.clearbit.com/slack.com', category: 'communication' },
  { name: 'Notion', logo: 'https://logo.clearbit.com/notion.so', category: 'productivity' },
  { name: 'Figma', logo: 'https://logo.clearbit.com/figma.com', category: 'design' },
  { name: 'GitHub', logo: 'https://logo.clearbit.com/github.com', category: 'development' },
  { name: 'Linear', logo: 'https://logo.clearbit.com/linear.app', category: 'productivity' },
  { name: 'Vercel', logo: 'https://logo.clearbit.com/vercel.com', category: 'development' },
  { name: 'AWS', logo: 'https://logo.clearbit.com/aws.amazon.com', category: 'development' },
  { name: 'Google Workspace', logo: 'https://logo.clearbit.com/google.com', category: 'productivity' },
  { name: 'Dropbox', logo: 'https://logo.clearbit.com/dropbox.com', category: 'storage' },
  { name: 'Zoom', logo: 'https://logo.clearbit.com/zoom.us', category: 'communication' },
  { name: 'Mailchimp', logo: 'https://logo.clearbit.com/mailchimp.com', category: 'marketing' },
  { name: 'HubSpot', logo: 'https://logo.clearbit.com/hubspot.com', category: 'marketing' },
  { name: 'Stripe', logo: 'https://logo.clearbit.com/stripe.com', category: 'finance' },
  { name: 'QuickBooks', logo: 'https://logo.clearbit.com/quickbooks.intuit.com', category: 'finance' },
  { name: '1Password', logo: 'https://logo.clearbit.com/1password.com', category: 'security' },
  { name: 'Mixpanel', logo: 'https://logo.clearbit.com/mixpanel.com', category: 'analytics' },
  { name: 'Intercom', logo: 'https://logo.clearbit.com/intercom.com', category: 'communication' },
  { name: 'Airtable', logo: 'https://logo.clearbit.com/airtable.com', category: 'productivity' },
  { name: 'Canva', logo: 'https://logo.clearbit.com/canva.com', category: 'design' },
  { name: 'Asana', logo: 'https://logo.clearbit.com/asana.com', category: 'productivity' },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: '1',
    name: 'Slack',
    logo: 'https://logo.clearbit.com/slack.com',
    cost: 12.50,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-02-01'),
    status: 'active',
    category: 'communication',
    usagePercentage: 92,
    createdAt: new Date('2024-03-15'),
    lastUsed: new Date('2025-01-18'),
    teamMembers: ['1', '2', '3'],
    priceHistory: [
      { date: new Date('2024-01-01'), oldPrice: 10.00, newPrice: 12.50 },
    ],
  },
  {
    id: '2',
    name: 'Notion',
    logo: 'https://logo.clearbit.com/notion.so',
    cost: 10.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-01-25'),
    status: 'active',
    category: 'productivity',
    usagePercentage: 78,
    createdAt: new Date('2024-02-01'),
    lastUsed: new Date('2025-01-19'),
    teamMembers: ['1', '2'],
  },
  {
    id: '3',
    name: 'Figma',
    logo: 'https://logo.clearbit.com/figma.com',
    cost: 15.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-02-05'),
    status: 'active',
    category: 'design',
    usagePercentage: 65,
    createdAt: new Date('2024-01-20'),
    lastUsed: new Date('2025-01-17'),
    teamMembers: ['2'],
  },
  {
    id: '4',
    name: 'GitHub',
    logo: 'https://logo.clearbit.com/github.com',
    cost: 4.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-01-28'),
    status: 'active',
    category: 'development',
    usagePercentage: 95,
    createdAt: new Date('2023-12-01'),
    lastUsed: new Date('2025-01-19'),
    teamMembers: ['1', '3'],
  },
  {
    id: '5',
    name: 'Linear',
    logo: 'https://logo.clearbit.com/linear.app',
    cost: 8.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-02-10'),
    status: 'active',
    category: 'productivity',
    usagePercentage: 88,
    createdAt: new Date('2024-05-01'),
    lastUsed: new Date('2025-01-19'),
    teamMembers: ['1', '2', '3'],
  },
  {
    id: '6',
    name: 'Vercel',
    logo: 'https://logo.clearbit.com/vercel.com',
    cost: 20.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-01-30'),
    status: 'active',
    category: 'development',
    usagePercentage: 72,
    createdAt: new Date('2024-04-15'),
    lastUsed: new Date('2025-01-18'),
    teamMembers: ['1'],
  },
  {
    id: '7',
    name: 'Dropbox',
    logo: 'https://logo.clearbit.com/dropbox.com',
    cost: 119.88,
    billingFrequency: 'annual',
    nextRenewal: new Date('2025-06-15'),
    status: 'active',
    category: 'storage',
    usagePercentage: 45,
    createdAt: new Date('2024-06-15'),
    lastUsed: new Date('2025-01-10'),
    notes: 'Team storage for design assets',
  },
  {
    id: '8',
    name: 'Zoom',
    logo: 'https://logo.clearbit.com/zoom.us',
    cost: 14.99,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-02-03'),
    status: 'active',
    category: 'communication',
    usagePercentage: 35,
    createdAt: new Date('2024-01-10'),
    lastUsed: new Date('2024-11-20'),
    notes: 'Consider canceling - low usage',
  },
  {
    id: '9',
    name: 'Mailchimp',
    logo: 'https://logo.clearbit.com/mailchimp.com',
    cost: 20.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-02-08'),
    status: 'paused',
    category: 'marketing',
    usagePercentage: 0,
    createdAt: new Date('2024-03-01'),
    lastUsed: new Date('2024-09-15'),
  },
  {
    id: '10',
    name: '1Password',
    logo: 'https://logo.clearbit.com/1password.com',
    cost: 35.88,
    billingFrequency: 'annual',
    nextRenewal: new Date('2025-08-20'),
    status: 'active',
    category: 'security',
    usagePercentage: 100,
    createdAt: new Date('2024-08-20'),
    lastUsed: new Date('2025-01-19'),
    teamMembers: ['1', '2', '3'],
  },
  {
    id: '11',
    name: 'Mixpanel',
    logo: 'https://logo.clearbit.com/mixpanel.com',
    cost: 25.00,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-01-22'),
    status: 'active',
    category: 'analytics',
    usagePercentage: 60,
    createdAt: new Date('2024-07-01'),
    lastUsed: new Date('2025-01-15'),
  },
  {
    id: '12',
    name: 'Canva',
    logo: 'https://logo.clearbit.com/canva.com',
    cost: 12.99,
    billingFrequency: 'monthly',
    nextRenewal: new Date('2025-02-12'),
    status: 'trial',
    category: 'design',
    usagePercentage: 25,
    createdAt: new Date('2025-01-12'),
    lastUsed: new Date('2025-01-16'),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'renewal',
    title: 'Notion renews in 6 days',
    description: 'Your Notion subscription ($10.00/mo) will automatically renew on Jan 25, 2025.',
    subscriptionId: '2',
    subscriptionName: 'Notion',
    createdAt: new Date('2025-01-19'),
    isRead: false,
    actionLabel: 'Review',
    actionType: 'view',
  },
  {
    id: '2',
    type: 'renewal',
    title: 'Mixpanel renews in 3 days',
    description: 'Your Mixpanel subscription ($25.00/mo) will automatically renew on Jan 22, 2025.',
    subscriptionId: '11',
    subscriptionName: 'Mixpanel',
    createdAt: new Date('2025-01-19'),
    isRead: false,
    actionLabel: 'Review',
    actionType: 'view',
  },
  {
    id: '3',
    type: 'unused',
    title: 'Zoom appears unused',
    description: 'You haven\'t used Zoom in over 60 days. Consider canceling to save $14.99/mo.',
    subscriptionId: '8',
    subscriptionName: 'Zoom',
    createdAt: new Date('2025-01-18'),
    isRead: false,
    actionLabel: 'Cancel',
    actionType: 'cancel',
  },
  {
    id: '4',
    type: 'duplicate',
    title: 'Potential duplicate detected',
    description: 'You have both Figma and Canva for design. Consider consolidating to save $12.99/mo.',
    subscriptionId: '12',
    subscriptionName: 'Canva',
    createdAt: new Date('2025-01-17'),
    isRead: true,
    actionLabel: 'Review',
    actionType: 'view',
  },
  {
    id: '5',
    type: 'price_increase',
    title: 'Slack price increased',
    description: 'Slack increased from $10.00 to $12.50/mo. Annual savings of $30 available.',
    subscriptionId: '1',
    subscriptionName: 'Slack',
    createdAt: new Date('2025-01-15'),
    isRead: true,
    actionLabel: 'View Details',
    actionType: 'view',
  },
  {
    id: '6',
    type: 'budget',
    title: 'Approaching budget limit',
    description: 'You\'ve used 85% of your monthly SaaS budget ($425 of $500).',
    createdAt: new Date('2025-01-14'),
    isRead: false,
    actionLabel: 'View Budget',
    actionType: 'view',
  },
];

export const mockBudgets: Budget[] = [
  {
    id: '1',
    name: 'Total SaaS Spending',
    limit: 500,
    spent: 425,
    period: 'monthly',
  },
  {
    id: '2',
    name: 'Development Tools',
    limit: 100,
    spent: 32,
    category: 'development',
    period: 'monthly',
  },
  {
    id: '3',
    name: 'Communication',
    limit: 75,
    spent: 42.49,
    category: 'communication',
    period: 'monthly',
  },
  {
    id: '4',
    name: 'Design Tools',
    limit: 50,
    spent: 27.99,
    category: 'design',
    period: 'monthly',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Alex Chen',
    email: 'alex@example.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    role: 'owner',
    subscriptions: ['1', '2', '4', '5', '6', '10'],
  },
  {
    id: '2',
    name: 'Sarah Kim',
    email: 'sarah@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    role: 'admin',
    subscriptions: ['1', '2', '3', '5', '10'],
  },
  {
    id: '3',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    role: 'member',
    subscriptions: ['1', '4', '5', '10'],
  },
];

export const mockSavingsInsights: SavingsInsight[] = [
  {
    id: '1',
    type: 'unused',
    title: 'Cancel unused Zoom subscription',
    description: 'Zoom hasn\'t been used in 60+ days.',
    potentialSavings: 179.88,
    subscriptionIds: ['8'],
    recommendation: 'Cancel Zoom and use Google Meet (included with Workspace) for video calls.',
  },
  {
    id: '2',
    type: 'duplicate',
    title: 'Consolidate design tools',
    description: 'You\'re paying for both Figma and Canva.',
    potentialSavings: 155.88,
    subscriptionIds: ['3', '12'],
    recommendation: 'Keep Figma for UI design and use Canva free tier for marketing graphics.',
  },
  {
    id: '3',
    type: 'alternative',
    title: 'Switch to annual billing',
    description: 'Save 20% by switching Slack to annual billing.',
    potentialSavings: 30,
    subscriptionIds: ['1'],
    recommendation: 'Switch from $12.50/mo to $120/year for annual savings.',
  },
  {
    id: '4',
    type: 'downgrade',
    title: 'Downgrade Dropbox plan',
    description: 'You\'re only using 45% of your Dropbox storage.',
    potentialSavings: 60,
    subscriptionIds: ['7'],
    recommendation: 'Downgrade to Dropbox Plus and save $60/year.',
  },
];

export const spendingTrendData = [
  { month: 'Aug', amount: 298 },
  { month: 'Sep', amount: 315 },
  { month: 'Oct', amount: 342 },
  { month: 'Nov', amount: 389 },
  { month: 'Dec', amount: 402 },
  { month: 'Jan', amount: 425 },
];

export const categoryBreakdownData = [
  { name: 'Communication', value: 42.49, color: '#6366f1' },
  { name: 'Productivity', value: 18.00, color: '#8b5cf6' },
  { name: 'Development', value: 24.00, color: '#a855f7' },
  { name: 'Design', value: 27.99, color: '#d946ef' },
  { name: 'Analytics', value: 25.00, color: '#ec4899' },
  { name: 'Storage', value: 9.99, color: '#f43f5e' },
  { name: 'Security', value: 2.99, color: '#f97316' },
];

export function calculateMonthlyTotal(subscriptions: Subscription[]): number {
  return subscriptions
    .filter(s => s.status === 'active' || s.status === 'trial')
    .reduce((total, sub) => {
      if (sub.billingFrequency === 'annual') {
        return total + sub.cost / 12;
      }
      return total + sub.cost;
    }, 0);
}

export function calculateAnnualProjection(subscriptions: Subscription[]): number {
  return subscriptions
    .filter(s => s.status === 'active' || s.status === 'trial')
    .reduce((total, sub) => {
      if (sub.billingFrequency === 'annual') {
        return total + sub.cost;
      }
      return total + sub.cost * 12;
    }, 0);
}
